### ISSUE TITLE
Device Server/Client Updates

### ISSUE THREAD

**Issue by mehrdadh** [mehrdadh/tlcpack-micro-ci#1]
- [x] Update server to check device status before adding to the inventory: #2 
- [x] Add enable/disable option for devices to support drivers issue cases: #3 
- [x] Fix poetry install: #4 
- [x] Randomize device assignment to avoid burning out one device.
